title: 'The Bass Station'
description: "A jekyll theme inspired by linux consoles for hackers, developers and script kiddies."
baseurl: "/jekyll-theme-console-demo-dark"
url: "https://b2a3e8.github.io"

header_pages:
  - index.md
  - discography.md
  - about.md
  - contact.md

style: dark  # dark (default), light or hacker
# listen_for_clients_preferred_style: true  # false (default) or true

footer:
  '<a href="https://soundcloud.com/justabasstronaut">soundcloud</a> | <a href="https://instagram.com/@thebasstronaut">instagram</a>'

# Build settings
markdown: kramdown
theme: jekyll-theme-console

# HECK NO! DISABLED!
# google_analytics: "UA-NNNNNNNN-N"
